model_or_framework_id: ${..model_or_framework_id}
model_or_framework_name: ${..model_or_framework_name}
hyperparameters:
  device: cuda
  number_of_classes: 2
  optimiser:
    type: Adam
    kwargs:
      lr: 0.00001
  criterion:
    apply_weights: False
    device: ${..device}
    metadataframe: ${.....data.metadataframe}
  model:
    number_of_classes: 2
