model_or_framework_id: ${..model_or_framework_id}
model_or_framework_name: ${..model_or_framework_name}
hyperparameters:
  criterion:
    apply_weights: True
    labeled_dataset_name: ${..dataset_name.labeled}
    device: ${..device}
    metadataframe: ${.....data.metadataframe}
    pseudo_label_approval_threshold: 0.95
    supervised_loss_label: malignancy
    unsupervised_loss_relative_weight: 0.5
    classification_loss_type: BCE # Options: BCE, BCE + Dice, Focal
    eta: 2 # Options: 0.25, 0.5, 1, 2, 5
    iota: 3 # Options: 1, 2, 3
  data_augmenter:
    data_size: ${.....data.size}
    weak_data_augmenter:
      data_size: ${......data.size}
      random_flip:
        probability: 0.5
      random_translate:
        maximum_fraction: 0.125
        fill: -1
    strong_data_augmenter:
      data_size: ${......data.size}
      number_of_transformations: 2
      auto_contrast:
        min_max_pixel_values: [ -1, 1 ]
      random_brightness:
        factor_range: [ 0.7, 1.3 ]
      random_contrast:
        factor_range: [ 0.7, 1.3 ]
      random_elastic_transform:
        alpha: 50.0
        sigma: 5.0
        fill: -1
      random_erasing:
        scale: [ 0.000976562, 0.000976562 ]
        ratio: [ 1.0, 1.0 ]
        value: -1
      random_gaussian_blur:
        kernel_size: 3
        sigma_range: [ 0.5, 1.0 ]
      random_posterize:
        bit_range: [ 4, 8 ]
      random_rotation:
        degrees: 30
        fill: -1
      random_shear:
        fraction_range: 0.3
      random_solarize:
        threshold_range: [ 0, 1 ]
      random_translate:
        maximum_fraction: 0.2
        fill: -1
  dataset_name:
    labeled: lidc_idri
    unlabeled: luna25
  device: cuda
  model:
    name: ResNet-18
    number_of_classes: 2
  optimizer:
    lr_scheduler:
      max_epochs: ${.....model_and_framework_pipeline.pytorch_lightning_trainer_kwargs.max_epochs}
    sgd:
      lr: 1e-5
      momentum: 0.9
      nesterov: True,
      weight_decay: 5e-4